
import { Event } from './types';

export const MOCK_EVENTS: Event[] = [
  {
    id: '1',
    eventName: 'Neon Nights Festival',
    description: 'Experience the pulse of the city with top tier electronic artists from around the globe.',
    image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    venue: 'The Cyber Loft',
    location: 'Brooklyn, NY',
    date: '2024-12-15',
    time: '10:00 PM',
    category: 'Electronic',
    price: '$85',
    link: '#'
  },
  {
    id: '2',
    eventName: 'Indie Soul Sessions',
    description: 'An intimate evening featuring breakthrough indie artists in a cozy acoustic setting.',
    image: 'https://images.unsplash.com/photo-1501612766622-27c94b2343bc?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    venue: 'Echo Chamber',
    location: 'Austin, TX',
    date: '2024-12-18',
    time: '8:00 PM',
    category: 'Indie Rock',
    price: '$35',
    link: '#'
  },
  {
    id: '3',
    eventName: 'Underground Bass',
    description: 'Deep bass and dubstep rhythms shaking the foundation of the warehouse district.',
    image: 'https://images.unsplash.com/photo-1571266028243-3716027f8e6c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    venue: 'Sub-Zero',
    location: 'Berlin, DE',
    date: '2024-12-20',
    time: '11:30 PM',
    category: 'Dubstep',
    price: '$25',
    link: '#'
  },
  {
    id: '4',
    eventName: 'Jazz Fusion Collective',
    description: 'Modern jazz meets electronic textures. A unique auditory experience for connoisseurs.',
    image: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    venue: 'Blue Note Modern',
    location: 'Chicago, IL',
    date: '2024-12-22',
    time: '7:30 PM',
    category: 'Live Jazz',
    price: '$40',
    link: '#'
  },
  {
    id: '5',
    eventName: 'Synthwave Sunset',
    description: 'Retro-futuristic beats to drive into the night. 80s nostalgia with a modern twist.',
    image: 'https://images.unsplash.com/photo-1563841930606-67e2bce48b78?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    venue: 'Palm Horizon',
    location: 'Miami, FL',
    date: '2024-12-24',
    time: '9:00 PM',
    category: 'Electronic',
    price: '$30',
    link: '#'
  },
  {
    id: '6',
    eventName: 'Urban Hip-Hop Showcase',
    description: 'The freshest rhymes and beats from the local underground hip-hop scene.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    venue: 'The Block',
    location: 'Atlanta, GA',
    date: '2024-12-26',
    time: '8:30 PM',
    category: 'Hip-Hop',
    price: '$45',
    link: '#'
  },
  {
    id: '7',
    eventName: 'Alternative Currents',
    description: 'Breaking boundaries with experimental rock and alternative sounds.',
    image: 'https://images.unsplash.com/photo-1493225255756-d9584f8606e9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    venue: 'Garage 42',
    location: 'Seattle, WA',
    date: '2024-12-28',
    time: '8:00 PM',
    category: 'Alternative',
    price: '$20',
    link: '#'
  },
  {
    id: '8',
    eventName: 'Techno Bunker',
    description: 'Hard hitting techno beats until sunrise. strictly underground vibes.',
    image: 'https://images.unsplash.com/photo-1594122230689-45899d9e6f69?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    venue: 'Vault 101',
    location: 'London, UK',
    date: '2024-12-30',
    time: '12:00 AM',
    category: 'Techno',
    price: '$30',
    link: '#'
  },
   {
    id: '9',
    eventName: 'Acoustic Reverie',
    description: 'Unplugged sessions with award-winning songwriters sharing the stories behind the songs.',
    image: 'https://images.unsplash.com/photo-1485579149621-3123dd979885?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    venue: 'The Living Room',
    location: 'Nashville, TN',
    date: '2025-01-05',
    time: '7:00 PM',
    category: 'Acoustic',
    price: 'Free',
    link: '#'
  },
  {
    id: '10',
    eventName: 'Cyberpunk Rave',
    description: 'Immersive audio-visual experience in a futuristic dystopian setting.',
    image: 'https://images.unsplash.com/photo-1533174072545-e8d4aa97edf9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    venue: 'Sector 7',
    location: 'Tokyo, JP',
    date: '2025-01-10',
    time: '11:00 PM',
    category: 'Electronic',
    price: '$60',
    link: '#'
  },
  {
    id: '11',
    eventName: 'Lo-Fi Chill Lounge',
    description: 'Relaxing beats and study vibes with live lo-fi producers mixing on the spot.',
    image: 'https://images.unsplash.com/photo-1516280440614-6697288d5d38?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    venue: 'Cloud 9 Cafe',
    location: 'Portland, OR',
    date: '2025-01-12',
    time: '6:00 PM',
    category: 'Electronic',
    price: '$15',
    link: '#'
  },
  {
    id: '12',
    eventName: 'Hard Rock Revolt',
    description: 'High energy guitar riffs and thundering drums for the ultimate rock experience.',
    image: 'https://images.unsplash.com/photo-1549488497-270831a29330?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    venue: 'The Anvil',
    location: 'Detroit, MI',
    date: '2025-01-15',
    time: '9:00 PM',
    category: 'Alternative',
    price: '$40',
    link: '#'
  },
  {
    id: '13',
    eventName: 'Smooth Jazz Night',
    description: 'Saxophone melodies and smooth piano keys for a sophisticated night out.',
    image: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    venue: 'Velvet Lounge',
    location: 'New Orleans, LA',
    date: '2025-01-18',
    time: '8:00 PM',
    category: 'Live Jazz',
    price: '$50',
    link: '#'
  },
  {
    id: '14',
    eventName: 'Rap Battles 2025',
    description: 'Local lyrical geniuses go head to head in this intense freestyle competition.',
    image: 'https://images.unsplash.com/photo-1525362081669-2b4764d55784?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    venue: 'The Basement',
    location: 'Bronx, NY',
    date: '2025-01-20',
    time: '9:30 PM',
    category: 'Hip-Hop',
    price: '$20',
    link: '#'
  },
  {
    id: '15',
    eventName: 'Deep House Dive',
    description: 'Submerged in rhythm. A night dedicated to deep house aficionados.',
    image: 'https://images.unsplash.com/photo-1558507652-2d9626c4e67a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    venue: 'Aquarium Club',
    location: 'Sydney, AU',
    date: '2025-01-22',
    time: '10:00 PM',
    category: 'Electronic',
    price: '$35',
    link: '#'
  }
];

export const CATEGORIES = ["All", "Electronic", "Indie Rock", "Hip-Hop", "Live Jazz", "Techno", "Alternative", "Dubstep", "Acoustic"];
